name: ebisu_ang
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_ang
description: >
  A library that supports code generation of Angular2 code

dependencies:

# custom <ebisu_ang dependencies>
# end <ebisu_ang dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <ebisu_ang dev dependencies>
# end <ebisu_ang dev dependencies>

dependency_overrides:
# custom <ebisu_ang dependency overrides>
# end <ebisu_ang dependency overrides>

transformers:

# custom <ebisu_ang transformers>
# end <ebisu_ang transformers>

