name: ebisu_ang
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_ang
description: >
  A library that supports code generation of Angular2 code

environment:
  sdk: '>=1.8.2 <2.0.0'

dependencies:

# custom <ebisu_ang dependencies>

ebisu: "^0.6.16"

# end <ebisu_ang dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <ebisu_ang dev dependencies>

  test: "any"
  
  drudge:
    git: git://github.com/patefacio/drudge

# end <ebisu_ang dev dependencies>

dependency_overrides:
# custom <ebisu_ang dependency overrides>

#  ebisu:
#    git: git://github.com/patefacio/ebisu
#    path: ../ebisu
  
# end <ebisu_ang dependency overrides>

transformers:

# custom <ebisu_ang transformers>
# end <ebisu_ang transformers>

