name: mortgage_calculator
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
environment:
  sdk: '>=1.8.2 <2.0.0'

dependencies:
  angular2: "2.0.0-beta.17"
  browser: "^0.10.0"

# custom <mortgage_calculator dependencies>
  dart_to_js_script_rewriter: ^1.0.1
# end <mortgage_calculator dependencies>

dev_dependencies:
  yaml: "any"

# custom <mortgage_calculator dev dependencies>

  drudge:
    git: git://github.com/patefacio/drudge

# end <mortgage_calculator dev dependencies>

dependency_overrides:
# custom <mortgage_calculator dependency overrides>
# end <mortgage_calculator dependency overrides>

transformers:
- angular2:
    entry_points:
      - web/main.dart


# custom <mortgage_calculator transformers>

- dart_to_js_script_rewriter

# end <mortgage_calculator transformers>

