name: balance_sheet
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
environment:
  sdk: '>=1.8.2 <2.0.0'

dependencies:
  angular2: "2.0.0-beta.17"
  browser: "^0.10.0"

# custom <balance_sheet dependencies>
# end <balance_sheet dependencies>

dev_dependencies:
  yaml: "any"

# custom <balance_sheet dev dependencies>

  angular2: "2.0.0-beta.0"
  angular2_material: "2.0.0-beta.0"

# end <balance_sheet dev dependencies>

dependency_overrides:
# custom <balance_sheet dependency overrides>
# end <balance_sheet dependency overrides>

transformers:
- angular2:
    entry_points:
      - web/main.dart


# custom <balance_sheet transformers>

- angular2:
    entry_points: web/main.dart

# end <balance_sheet transformers>

