name: balance_sheet
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:

# custom <balance_sheet dependencies>
# end <balance_sheet dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"

# custom <balance_sheet dev dependencies>
# end <balance_sheet dev dependencies>

dependency_overrides:
# custom <balance_sheet dependency overrides>
# end <balance_sheet dependency overrides>

transformers:

# custom <balance_sheet transformers>
# end <balance_sheet transformers>

